from tortoise.models import Model
from tortoise import fields


class Student(Model):
    STD_ID = fields.BigIntField(null=True)
    MAN_ID = fields.BigIntField(null=True)
    SURNAME = fields.CharField(max_length=60)
    NAME = fields.CharField(max_length=60)
    PATRON = fields.CharField(max_length=60)
    SEX = fields.CharField(max_length=10, null=True)
    STATE_NAME_SH = fields.CharField(max_length=10, null=True)
    PHONE = fields.CharField(max_length=80, null=True)
    S_GRP_ID = fields.BigIntField(null=True)
    STATUS = fields.CharField(max_length=50, null=True)
    KATEG_ST = fields.CharField(max_length=50, null=True)
    NEUD = fields.CharField(max_length=10, null=True)
    DIFF_PLAN = fields.CharField(max_length=10, null=True)
    GRAFIK = fields.CharField(max_length=10, null=True)
    DOCUMENT = fields.CharField(max_length=10, null=True)
    MIL_KAF = fields.CharField(max_length=10, null=True)
    D_BEGIN = fields.DateField(null=True)
    D_END = fields.DateField(null=True)
    CHIEF = fields.CharField(max_length=10, null=True)
    KATEGOR = fields.CharField(max_length=50, null=True)
    DATA_PO = fields.DateField(null=True)
    BASE = fields.CharField(max_length=50, null=True)
    DATA_S = fields.DateField(null=True)
    COURCE = fields.BigIntField(null=True)
    DSPE_ID = fields.BigIntField(null=True)
    GRP_NAME = fields.CharField(max_length=20, null=True)
    GOD_POST = fields.DateField(null=True)
    FS_ID = fields.BigIntField(null=True)
    LOCATION = fields.CharField(max_length=100, null=True)
    SHORT_NAME = fields.CharField(max_length=20, null=True)
    FS_NAME = fields.CharField(max_length=100, null=True)
    FORM_STUDY = fields.CharField(max_length=10, null=True)
    SPEED = fields.CharField(max_length=10, null=True)
    LENGTH = fields.FloatField(null=True)
    BASEO = fields.CharField(max_length=10, null=True)
    SPE_SHIFR = fields.CharField(max_length=20, null=True)
    SPE_SHIFR7 = fields.CharField(max_length=20, null=True)
    FAK_ID = fields.BigIntField(null=True)
    SHIFR_SP_UNI = fields.CharField(max_length=30, null=True)
    NAME_SP_UNI = fields.CharField(max_length=30, null=True)
    FAC_NAME_SH = fields.CharField(max_length=30, null=True)
    INST_NAME = fields.CharField(max_length=30, null=True)
    FAC_NAME = fields.CharField(max_length=200, null=True)
    SPEC_NAME = fields.CharField(max_length=8000, null=True)
    SPZ_NAME = fields.CharField(max_length=8000, null=True)
    QUALIF = fields.CharField(max_length=200, null=True)
    CODE_SPEC = fields.CharField(max_length=20, null=True)
    MARITAL = fields.CharField(max_length=20, null=True)
    BIRTHDAY = fields.DateField(null=True)
    DOPUSK_DIP = fields.BigIntField(null=True)
    AC_STEP = fields.CharField(max_length=30, null=True)
    LAST_CO_ID = fields.BigIntField(null=True)
    ENTER_YEAR = fields.BigIntField(null=True)
    FSDS_ID = fields.BigIntField(null=True)
    STIP_1K = fields.CharField(max_length=10, null=True)
    LEV = fields.CharField(max_length=20, null=True)
    VIRT_GRP = fields.IntField(null=True)
    snils4 = fields.CharField(max_length=4, null=True)
    birthday_day = fields.IntField(null=True)
    birthday_month = fields.IntField(null=True)

    class Meta:
        table = "ora_students"
